#!/bin/bash

function echo_blue_bold {
    echo -e "\033[1;34m$1\033[0m"
}
echo
echo_blue_bold "Enter private key:"
read privateKeys
echo
echo_blue_bold "Enter transaction data (in hex):"
read transactionData
echo
echo_blue_bold "Enter number of transactions to send:"
read numberOfTransactions
echo

if [ ! -f privatekeys.txt ]; then
  echo_blue_bold "Error: privatekeys.txt file not found!"
  exit 1
fi

if ! npm list ethers@5.5.4 >/dev/null 2>&1; then
  echo_blue_bold "Installing ethers..."
  npm install ethers@5.5.4
  echo
else
  echo_blue_bold "Ethers is already installed."
fi
echo

temp_node_file=$(mktemp /tmp/node_script.XXXXXX.js)

cat << EOF > $temp_node_file
const fs = require("fs");
const ethers = require("ethers");
const privateKeys = "${privateKeys}";
const providerURL = "https://rpc-holesky.morphl2.io";
const provider = new ethers.providers.JsonRpcProvider(providerURL);
const contractAddress = "0xea10cc1f6D4BbC5D3de25cC88d40d51eB38DCb7b";
const transactionData = "${transactionData}";
const numberOfTransactions = ${numberOfTransactions};

async function sendTransaction(wallet) {
    const tx = {
        to: contractAddress,
        value: 0,
        gasLimit: ethers.BigNumber.from(250000),
        gasPrice: ethers.utils.parseUnits("0.15", 'gwei'),
        data: transactionData,
    };

    try {
        const transactionResponse = await wallet.sendTransaction(tx);
        const walletAddress = wallet.address;
        console.log("\033[1;35mTx Hash:\033[0m", transactionResponse.hash);
        const receipt = await transactionResponse.wait();
        console.log("");
    } catch (error) {
        console.error("Error sending transaction:", error);
    }
}

async function main() {
    for (const key of privateKeys) {
        const wallet = new ethers.Wallet(key, provider);
        for (let i = 0; i < numberOfTransactions; i++) {
            console.log("Sending transaction", i + 1, "of", numberOfTransactions", "on", wallet.address);
            await sendTransaction(wallet);
        }
    }
}

main().catch(console.error);
EOF

NODE_PATH=$(npm root -g):$(pwd)/node_modules node $temp_node_file

rm $temp_node_file
echo
echo_blue_bold "DONE"
echo

